package dev.santiescobares.ubesweb.enums;

public enum Role {
    DEVELOPER,
    PRESIDENT,
    VICE_PRESIDENT,
    SECRETARY,
    PROSECRETARY,
    TREASURER,
    PRO_TREASURER,
    SPORT_SECRETARY,
    SPORT_PROSECRETARY,
    CULTURE_SECRETARY,
    CULTURE_PROSECRETARY,
    ENV_SECRETARY,
    ENV_PROSECRETARY,
    PPRR_SECRETARY,
    PPRR_PROSECRETARY,
    PRESS_SECRETARY,
    PRESS_PROSECRETARY,
    IIRR_SECRETARY,
    IIRR_PROSECRETARY,
    ADMIN_SECRETARY,
    ADMIN_PROSECRETARY,
    USER;
}
